App.MVC/Controllers/ProfissionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using App.MVC.Util;
using App.MVC.ViewModels;
using AutoMapper;
using ControleDeSalao.Application.Interface;
using ControleDeSalao.Domain.Entities;
using ControleDeSalao.Infra.Cross.Security;

namespace App.MVC.Controllers
{
    public class ProfissionalController : Controller
    {
        private readonly IProfissionalAppService _profissionalAppService;
        

        public ProfissionalController(IProfissionalAppService profissionalAppService)
        {
            _profissionalAppService = profissionalAppService;
            
        }

        // GET: Profissional
        public async Task<ActionResult> Index()
        {
            try
            {
                if (!Cookies.IdUsuarioLogado.HasValue)
                    return RedirectToAction("Login", "Usuario");

                if (Cookies.DataBloqueio <= DateTime.Today)
                    return RedirectToAction("Bloqueio", "Home");

                var profissionalViewModels = Mapper.Map<IEnumerable<Profissional>, IEnumerable<ProfissionalViewModel>>(await _profissionalAppService.GetAll());

                return View(profissionalViewModels);
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<ActionResult> Detalhe(int id)
        {
            try
            {
                var pro = Mapper.Map<Profissional, ProfissionalViewModel>(await _profissionalAppService.GetById(id));
                pro.SDataContratacao = pro.DataContratacao.HasValue ? pro.DataContratacao.Value.ToString("dd/MM/yyyy") : string.Empty;
                return PartialView(pro);
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return View("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Detalhe(ProfissionalViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Session["TodosProfissionais"] = null;
                    if (!string.IsNullOrEmpty(model.SDataContratacao))
                    {
                        DateTime dtContratacao;
                        DateTime.TryParse(model.SDataContratacao, out dtContratacao);
                        model.DataContratacao = dtContratacao > DateTime.MinValue ? dtContratacao : (DateTime?)null;
                    }

                    var profissional = Mapper.Map<ProfissionalViewModel, Profissional>(model);

                    await _profissionalAppService.Save(profissional);
                    TempData["swal"] = SweetAlert.MensagemSucesso("As informações foram salvas!");
                    ModelState.Clear();
                    
                    return RedirectPermanent("Index");
                }
                return RedirectPermanent("Index");
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return RedirectPermanent("Index");
            }
        }

        public async Task<ActionResult> Excluir(int id)
        {
            try
            {
                var profissional = await _profissionalAppService.GetById(id);
                profissional.Status = false;
                await _profissionalAppService.Save(profissional);
                Session["TodosProfissionais"] = null;
                return Json(profissional, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

App.MVC/Views/Profissional/Detalhe.cshtml
@model App.MVC.ViewModels.ProfissionalViewModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Profissional</h4>
        </div>
        @using (Html.BeginForm("Detalhe", "Profissional", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Status)
            @Html.HiddenFor(m => m.EmpresaId)
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", @required = "required" })
                            <label class="control-label">Nome ou Apelido<span class="required"> * </span></label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.CPF, new { @class = "form-control", @onkeyup = "mascara(this, cpf);", @maxlength = 14, @onblur = "ValidarCPF(this)" })
                            <label class="control-label">CPF</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.RG, new { @class = "form-control", @maxlength="16" })
                            <label class="control-label">RG</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.Celular, new { @class = "form-control", onkeyup = "mascara(this, mtel);", maxlength = "15" })
                            <label class="control-label">Celular</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control", onkeyup = "mascara(this, mtel);", maxlength = "15" })
                            <label class="control-label">Tel. Residencial</label>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            <label class="control-label">Email</label>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.Endereco, new { @class = "form-control" })
                            <label class="control-label">Endereço Completo</label>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input ">
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Comissao, new { @class = "form-control", maxlength = "3", @onkeyup = "mascara(this, soNumeros);" })
                                <label>Comissão dos serviços</label>
                                <span class="help-block">% Caso seja fixa para todos os serviços</span>
                                <i id="iconComissao">%</i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input ">
                            <div class="input-icon left">
                                @Html.TextBoxFor(model => model.Salario, new { @class = "form-control", @onkeyup = "mascara(this, moeda);" })
                                <label>Salário fixo</label>
                                <span class="help-block">Valor fixo pago por mês</span>
                                <i id="iconComissao">R$</i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input ">
                            @Html.TextBoxFor(model => model.SDataContratacao, new { @class = "form-control", @onkeyup = "mascara(this, data);", onblur = "validaData(this,this.value)", maxlength = "10" })
                            <label class="control-label">Data da Contratação</label>
                        </div>
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal" id="btnCancelar">Cancelar</button>
                    <button type="submit" class="btn blue">Salvar Profissional</button>
                </div>
            </div>
        }
    </div>
</div>
<script>
</script>

App.MVC/Views/Profissional/Index.cshtml
@using App.MVC.ViewModels
@using ControleDeSalao.Infra.Cross.Security
@model IEnumerable<App.MVC.ViewModels.ProfissionalViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/datatables")
@Scripts.Render("~/bundles/datatable")
@Scripts.Render("~/bundles/mascaras")

<div class="page-content">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-group font-blue-hoki"></i>
                <span class="caption-subject font-blue-sharp bold uppercase">Meus Profissionais</span>
                <span class="caption-helper">O Seu time, a sua equipe...</span>
            </div>
            <div class="actions">
                <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-xs-12 col-md-12 text-left">
                    <br />
                    <a class="btn blue" data-toggle="modal" href="#modalProfissional">
                        <i class="fa fa-plus"></i>
                        Incluir um novo profissional
                    </a>
                </div>
            </div>
            <br />
            <div>
                <table class="table table-striped table-bordered table-hover table-condensed" id="tableProfissionais">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Email</th>
                            <th>Telefone</th>
                            <th>Celular</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Nome</td>
                                <td>@item.CPF</td>
                                <td>@item.Email</td>
                                <td>@item.Telefone</td>
                                <td>@item.Celular</td>
                                <td class="text-right">
                                    <a class="btn btn-xs blue tooltips editar" data-id="@item.Id" data-placement="top" data-original-title="Editar os dados do Profissional">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a class="btn btn-xs red-soft tooltips excluir" data-placement="top" data-original-title="Excluir" data-item-id="@item.Id">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/Profissional-Index")

<div class="modal fade" id="modalEdit">
</div>

<div class="modal fade" id="modalProfissional" tabindex="-1" role="dialog" aria-labelledby="modalProfissionalLabel" aria-hidden="true">
    @Html.Partial("Detalhe", new ProfissionalViewModel())
</div>