App.MVC/Controllers/AgendaController.cs
using App.MVC.Util;
using App.MVC.ViewModels;
using AutoMapper;
using ControleDeSalao.Application.Interface;
using ControleDeSalao.Domain.Entities;
using ControleDeSalao.Infra.Cross.Security;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace App.MVC.Controllers
{
    public class AgendaController : Controller
    {
        private readonly IProfissionalAppService _profissionalAppService;
        private readonly IAgendaAppService _agendaAppService;
        private readonly IClienteAppService _clienteAppService;
        private readonly IServicoAppService _servicoAppService;

        private readonly IEmpresaAppService _empresaAppService;

        public AgendaController(IProfissionalAppService profissionalAppService, IAgendaAppService agendaAppService, IClienteAppService clienteAppService, IServicoAppService servicoAppService, IProfissionalCategoriaAppService profissionalCategoriaAppService, IEmpresaAppService empresaAppService)
        {
            _profissionalAppService = profissionalAppService;
            _agendaAppService = agendaAppService;
            _clienteAppService = clienteAppService;
            _servicoAppService = servicoAppService;
            _empresaAppService = empresaAppService;
        }

        // GET: Agenda
        public async Task<ActionResult> Index()
        {
            try
            {
                if (!Cookies.IdUsuarioLogado.HasValue)
                    return RedirectToAction("Login", "Usuario");

                if (Cookies.DataBloqueio <= DateTime.Today)
                    return RedirectToAction("Bloqueio", "Home");

                var profissionais = (List<ProfissionalViewModel>)Session["TodosProfissionais"] ?? new List<ProfissionalViewModel>();
                if (profissionais.Count <= 0)
                {
                    if (!Cookies.IdProfissionalLogado.HasValue)
                    {
                        profissionais = Mapper.Map<IEnumerable<Profissional>, IEnumerable<ProfissionalViewModel>>(await _profissionalAppService.GetAll()).ToList();

                        foreach (var profissional in profissionais)
                        {
                            profissional.HorarioMarcado = Mapper.Map<IEnumerable<Agenda>, IEnumerable<AgendaViewModel>>(await _agendaAppService.GetByProfissionalIdAndPeriodo(profissional.Id, DateTime.Today, DateTime.Today.AddDays(6))).ToList();
                        }
                        Session["TodosProfissionais"] = profissionais;
                    }
                    else
                    {
                        var profissional = Mapper.Map<Profissional, ProfissionalViewModel>(await _profissionalAppService.GetById(Cookies.IdProfissionalLogado.Value));
                        profissional.HorarioMarcado = Mapper.Map<IEnumerable<Agenda>, IEnumerable<AgendaViewModel>>(await _agendaAppService.GetByProfissionalIdAndPeriodo(profissional.Id, DateTime.Today, DateTime.Today.AddDays(6))).ToList();
                        profissionais.Add(profissional);
                        Session["TodosProfissionais"] = profissionais;
                    }
                }

                Session["TodosServicos"] = Session["TodosServicos"] ?? Mapper.Map<IEnumerable<Servico>, IEnumerable<ServicoViewModel>>(await _servicoAppService.GetAll()).OrderBy(m => m.CategoriaId);
                var empresa = Mapper.Map<Empresa, EmpresaViewModel>(await _empresaAppService.GetById(Cookies.IdEmpresaLogada.Value));
                ViewBag.QtdSMS = empresa.QtdSMSPago + empresa.QtdSMSBonus;
                return View();
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Detalhe(AgendaViewModel model)
        {
            try
            {
                return await SalvarAgenda(model);
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return View(model);
            }
        }

        private async Task<ActionResult> SalvarAgenda(AgendaViewModel model)
        {
            var empresa =await _empresaAppService.GetById(Cookies.IdEmpresaLogada.Value);
            var age = await _agendaAppService.GetById(model.Id);
            var cli = await _clienteAppService.GetByNome(model.NomeCliente);
            if (cli == null)
            {
                cli = new Cliente
                {
                    Nome = model.NomeCliente,
                    Celular = model.CelularCliente
                };
                cli.Id = await _clienteAppService.Save(cli);
            }

            if (!string.IsNullOrEmpty(model.CelularCliente) && string.IsNullOrEmpty(cli.Celular))
            {
                cli.Celular = model.CelularCliente;
                await _clienteAppService.Save(cli);
            }

            var ser = await _servicoAppService.GetByNome(model.NomeServico);
            if (ser.Valor == 0)
            {
                ser.Valor = model.Valor;
                ser.HoraDuracao = Convert.ToInt32(model.Duracao.Split(':')[0]);// model.HoraDuracao;
                ser.MinutoDuracao = Convert.ToInt32(model.Duracao.Split(':')[1]);// model.MinutoDuracao;
                ser.ValorParaProfissional = Convert.ToDouble(model.NovaComissao);
                await _servicoAppService.Save(ser);
            }

            if (age == null)
                age = new Agenda();

            age.ProfissionalId = Convert.ToInt32(model.Parametros.Split('|')[1]);
            age.ServicoId = ser.Id;
            age.ClienteId = cli.Id;
            age.Data = Convert.ToDateTime(model.Parametros.Substring(8, 2) + model.Parametros.Substring(4, 3) + model.Parametros.Substring(11, 4)); //Convert.ToDateTime(model.Parametros.Split('|')[3]);
            age.Valor = model.Valor;
            age.HoraInicial = Convert.ToInt32(model.Parametros.Substring(16, 2) + model.Parametros.Substring(19, 2));
            age.HoraFinal = UtilAgenda.CalcularHoraFinal(age.HoraInicial, Convert.ToInt32(model.Duracao.Split(':')[0]), Convert.ToInt32(model.Duracao.Split(':')[1]));
            age.Observacao = model.Observacao;
            age.EnviarSMS = model.EnviarSMS;
            age.EnviouSMS = false;

            var emp = await _empresaAppService.GetById(Cookies.IdEmpresaLogada.Value);
            var msg = emp.SmsAgenda.Replace("[Cliente]", cli.Nome)
                    .Replace("[Salao]", Cookies.NomeEmpresaLogada)
                    .Replace("[Dia]", age.Data.ToString("dd/MM/yyyy"))
                    .Replace("[Horario]", age.HoraInicial.ToString("00:00"));

            if (age.EnviarSMS.HasValue && age.EnviarSMS.Value && age.Data == DateTime.Today &&
                !string.IsNullOrEmpty(model.CelularCliente) && model.CelularCliente.Length >= 14)
            {
                age.EnviouSMS = UtilAgenda.EnviarSMS(msg, model.CelularCliente, string.Empty, string.Empty);
                if (empresa.QtdSMSBonus > 0)
                    empresa.QtdSMSBonus -= 1;
                else if (empresa.QtdSMSPago > 0)
                    empresa.QtdSMSPago -= 1;

                await _empresaAppService.Save(empresa);
            }
            else if (age.EnviarSMS.HasValue && age.EnviarSMS.Value && age.Data > DateTime.Today)
            {
                age.EnviouSMS = UtilAgenda.EnviarSMS(msg, model.CelularCliente, age.Data.ToString("dd-MM-yyyy"), "08:30");
                if (empresa.QtdSMSBonus > 0)
                    empresa.QtdSMSBonus -= 1;
                else if (empresa.QtdSMSPago > 0)
                    empresa.QtdSMSPago -= 1;

                await _empresaAppService.Save(empresa);
            }

            await _agendaAppService.Save(age);


            return RedirectToAction("Index");
        }

        public async Task<ActionResult> ResgataAgenda(int id, string start, string end)
        {
            try
            {
                var agendas = Mapper.Map<IEnumerable<Agenda>, IEnumerable<AgendaViewModel>>(await _agendaAppService.GetByProfissionalIdAndPeriodo(id, Convert.ToDateTime(start.Substring(8, 2) + start.Substring(4, 3) + start.Substring(11, 4)), Convert.ToDateTime(end.Substring(8, 2) + end.Substring(4, 3) + end.Substring(11, 4))));
                return Json(agendas, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        public async Task<ActionResult> CancelarAgenda(int id)
        {
            try
            {
                var agenda = await _agendaAppService.GetById(id);

                if (agenda != null)
                {
                    agenda.Status = false;
                    await _agendaAppService.Save(agenda);
                }
                return Json(agenda, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        public async Task<ActionResult> AtualizarAgenda(int id, string start, string end)
        {
            try
            {
                var agenda = await _agendaAppService.GetById(id);

                if (agenda != null)
                {
                    agenda.Data = Convert.ToDateTime(start.Substring(8, 2) + start.Substring(4, 3) + start.Substring(11, 4));
                    agenda.HoraInicial = Convert.ToInt32(start.Substring(16, 2) + start.Substring(19, 2));

App.MVC/Views/Agenda/_DetalheAgenda.cshtml
@using App.MVC.ViewModels
@model AgendaViewModel

@Styles.Render("~/Content/typeahead")
@Scripts.Render("~/bundles/typeahead")
@Scripts.Render("~/bundles/mascaras")
@Styles.Render("~/Content/bootstrap-timepicker")
@Scripts.Render("~/bundles/bootstrap-timepicker")
<script src="~/assets/pages/scripts/components-date-time-pickers.min.js"></script>
@Styles.Render("~/Content/bootstrap-select")
@Scripts.Render("~/bundles/bootstrap-select")
@Styles.Render("~/Content/bootstrap-switch")
@Scripts.Render("~/bundles/bootstrap-switch")


@using (Html.BeginForm("Detalhe", "Agenda"))
{
    @Html.HiddenFor(m => m.Parametros, new { @id = "Parametros", @name = "Parametros" })
    <div class="row">
        <div class="col-md-8">
            <div class="form-group form-md-line-input">
                <label for="NomeCliente" style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Nome do Cliente</label>
                <input type="text" class="form-control" id="NomeCliente" name="NomeCliente" required>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group form-md-line-input ">
                <label for="CelularCliente" style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Celular do Cliente</label>
                <input type="text" class="form-control" id="CelularCliente" name="CelularCliente" onkeyup="mascara(this, mtel);" maxlength="15" placeholder="">

            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="NomeServico" style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Serviço</label>
                <select class="bs-select form-control" data-live-search="true" data-size="8" id="NomeServico" name="NomeServico" required>
                    <option value=""></option>
                    @foreach (var serv in (IEnumerable<ServicoViewModel>)Session["TodosServicos"])
                    {
                        <option>@serv.Descricao</option>
                    }
                </select>

            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-6 col-md-6">
            <div class="form-group form-md-line-input">
                <div class="input-group">
                    <input type="text" class="form-control timepicker timepicker-24" id="Duracao" name="Duracao" value="0:00" required>
                    <span class="input-group-btn">
                        <button class="btn default" type="button">
                            <i class="fa fa-clock-o"></i>
                        </button>
                    </span>
                    <label for="duracao">Duração</label>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-6">
            <div class="form-group form-md-line-input form-md-floating-label ">
                <div class="input-icon right">
                    <input type="text" class="form-control" id="NovaComissao" name="NovaComissao" style="display: none;" onkeyup="mascara(this, soNumeros);">
                    <label for="NovaComissao" id="lblComissao" style="display: none;">Comissão do profissional</label>
                    <span class="help-block">% para o profissional...</span>
                    <i id="iconComissao" style="display: none;">%</i>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-6 col-md-6">
            <div class="form-group form-md-line-input ">
                <input type="text" class="form-control" id="Valor" name="Valor" required onkeyup="mascara(this, moeda);">
                <label for="Valor">Valor em R$</label>
                <span class="help-block">Valor que você cobra pelo serviço...</span>
            </div>
        </div>
        <div class="col-xs-6 col-md-6" style="vertical-align: bottom !important">
            <br />
            <label style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Deseja enviar SMS?</label>
            <input type="checkbox" class="make-switch" data-on-text="&nbsp;Sim&nbsp;&nbsp;" data-off-text="&nbsp;Não&nbsp;" value="false" disabled="@(ViewBag.QtdSMS <= 0 ? true : false)">
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <div class="form-group form-md-line-input form-md-floating-label">
                <textarea class="form-control" rows="3" id="Observacao" name="Observacao"></textarea>
                <label for="Observacao">Observação</label>
            </div>
        </div>
    </div>
    <br />
    <div class="modal-footer">
        <button type="button" class="btn dark btn-outline" data-dismiss="modal" id="btnCancelar">Cancelar</button>
        <button type="submit" class="btn blue">Criar Agenda</button>
    </div>
    <input type="hidden" id="EnviarSMS" name="EnviarSMS">
    @Scripts.Render("~/bundles/Agenda-Detalhe")
}