App.MVC/Controllers/ComissaoController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using App.MVC.Util;
using App.MVC.ViewModels;
using AutoMapper;
using ControleDeSalao.Application.Interface;
using ControleDeSalao.Domain.Entities;
using ControleDeSalao.Infra.Cross.Security;
using Enum = ControleDeSalao.Domain.Enums.Enum;

namespace App.MVC.Controllers
{
    public class ComissaoController : Controller
    {
        private readonly IProfissionalAppService _profissionalAppService;
        
        private readonly IComissaoAppService _comissaoAppService;
        private readonly IFinanceiroAppService _financeiroAppService;
        private readonly IPlanoDeContaAppService _planoDeContaAppService;

        public ComissaoController(IProfissionalAppService profissionalAppService,  IComissaoAppService comissaoAppService, IFinanceiroAppService financeiroAppService, IPlanoDeContaAppService planoDeContaAppService)
        {
            _profissionalAppService = profissionalAppService;
            
            _comissaoAppService = comissaoAppService;
            _financeiroAppService = financeiroAppService;
            _planoDeContaAppService = planoDeContaAppService;
        }

        // GET: Comissao
        public async Task<ActionResult> Index()
        {
            if (!Cookies.IdUsuarioLogado.HasValue)
                return RedirectToAction("Login", "Usuario");

            if (Cookies.DataBloqueio <= DateTime.Today)
                return RedirectToAction("Bloqueio", "Home");

            //var profissionalViewModels = Mapper.Map<IEnumerable<Profissional>, IEnumerable<ProfissionalViewModel>>(await _profissionalAppService.GetAll());
            var profissionais = new List<ProfissionalViewModel>();
            if (profissionais.Count <= 0)
            {
                if (!Cookies.IdProfissionalLogado.HasValue)
                {
                    profissionais = Mapper.Map<IEnumerable<Profissional>, IEnumerable<ProfissionalViewModel>>(await _profissionalAppService.GetAll()).ToList();
                    Session["TodosProfissionais"] = profissionais;
                }
                else
                {
                    var profissional = Mapper.Map<Profissional, ProfissionalViewModel>(await _profissionalAppService.GetById(Cookies.IdProfissionalLogado.Value));
                    profissionais.Add(profissional);
                    Session["TodosProfissionais"] = profissionais;
                }
            }
            var comissoesViewModel = Mapper.Map<IEnumerable<Comissao>, IEnumerable<ComissaoViewModel>>(await _comissaoAppService.GetByStatus(Enum.StatusComissao.Aberto)).ToList();

            var viewModels = profissionais as IList<ProfissionalViewModel> ?? profissionais.ToList();
            foreach (var item in viewModels)
            {
                item.Comissoes = comissoesViewModel.Where(m => m.ProfissionalId == item.Id).ToList();

            }

            return View(profissionais);
        }

        public async Task<ActionResult> Detalhe(int id)
        {
            try
            {
                var profissional = Mapper.Map<Profissional, ProfissionalViewModel>(await _profissionalAppService.GetById(id));
                profissional.Comissoes = Mapper.Map<IEnumerable<Comissao>, IEnumerable<ComissaoViewModel>>(await _comissaoAppService.GetByProfissionalIdAndSatus(id, Enum.StatusComissao.Aberto)).ToList();
                return PartialView(profissional);
            }
            catch (Exception ex)
            {

                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return View("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Detalhe(ProfissionalViewModel model)
        {
            try
            {
                var planoDeContas = Mapper.Map<IEnumerable<PlanoDeConta>, IEnumerable<PlanoDeContaViewModel>>(await _planoDeContaAppService.GetByTipo(Enum.TipoCreditoDebito.Débito)).ToList();
                var plano = planoDeContas.FirstOrDefault(m => m.TelaPadrao == Enum.TelaPadrao.Comissão);
                var pagarComissoes = model.Comissoes.Where(m => m.Selecionada);
                var dtPagamento = string.IsNullOrEmpty(model.SDataPagamento) ? DateTime.Today : Convert.ToDateTime(model.SDataPagamento);

                Session["comissaoPagaProfissional"] = model.Id;
                Session["comissaoPagaData"] = dtPagamento;

                foreach (var com in pagarComissoes)
                {
                    var comissao = Mapper.Map<Comissao, ComissaoViewModel>(await _comissaoAppService.GetById(com.Id));

                    var financeiro = new Financeiro();
                    if (DateTime.Today == dtPagamento)
                    {
                        financeiro.ValorPago = comissao.Valor;
                        financeiro.DataVencimento = DateTime.Today;
                        financeiro.DataPagamento = DateTime.Today;
                        financeiro.Status = Enum.StatusFinanceiro.Pago;
                    }
                    else
                    {
                        financeiro.DataVencimento = dtPagamento;
                        financeiro.Status = Enum.StatusFinanceiro.Aberto;
                    }

                    financeiro.ProfissionalId = model.Id;
                    financeiro.PlanoDeContaId = plano.Id;
                    financeiro.FormaDePagamento = model.FormaDePagamento;
                    financeiro.Valor = comissao.Valor;
                    financeiro.Tipo = plano.Tipo;
                    financeiro.NomeQuem = model.Nome;
                    financeiro.Descricao = comissao.Descricao;
                    await _financeiroAppService.Save(financeiro);
                    comissao.Status = Enum.StatusComissao.Pago;
                    comissao.DataPagamento = dtPagamento;
                    await _comissaoAppService.Save(Mapper.Map<ComissaoViewModel, Comissao>(comissao));

                }
                TempData["swal"] = SweetAlert.MensagemSucessoComissao("As comissões foram pagas com sucesso! Os valores já foram automaticamente lançados no seu financeiro.");

                ModelState.Clear();
                return RedirectPermanent("Index");
            }
            catch (Exception ex)
            {
                TempData["swal"] = SweetAlert.MensagemErroNaoTratado(ex.Message);
                return RedirectPermanent("Index");
            }
        }

        public async Task<ActionResult> Recibo()
        {
            var profissionalId = Convert.ToInt32(Session["comissaoPagaProfissional"]);
            var dtPagamento = Convert.ToDateTime(Session["comissaoPagaData"]);
            var comissoesViewModel = Mapper.Map<IEnumerable<Comissao>, IEnumerable<ComissaoViewModel>>(await _comissaoAppService.GetByProfissinalAndPagamento(profissionalId, dtPagamento)).ToList();

            return View("_ReciboComissao", comissoesViewModel);
        }
    }
}

App.MVC/Views/Comissao/Detalhe.cshtml
@model  App.MVC.ViewModels.ProfissionalViewModel

@Scripts.Render("~/bundles/mascaras")
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Pagar Comissões</h4>
        </div>
        @using (Html.BeginForm("Detalhe", "Comissao", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Nome)
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            <label for="SData" style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Forma de Pagamento</label>
                            @Html.EnumDropDownListFor(m => m.FormaDePagamento, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input form-md-floating-label">
                            <label for="SDataPagamento" style="font: 'Open Sans', sans-serif 14px; color: #9c9999">Data de pagamento</label>
                            @Html.TextBoxFor(model => model.SDataPagamento, DateTime.Today.ToString("d"), new { @class = "form-control", @onkeyup = "mascara(this, data);", onblur = "validaData(this,this.value)", maxlength = "10", @required = "required", @id = "SDataPagamento" })
                        </div>
                    </div>
                </div>
                <br />
                @if (Model.Comissoes.Any())
                {
                    <table class="table table-striped">
                        <tr>
                            <th>
                                <div class="md-checkbox">
                                    <input type="checkbox" id="checkall" class=" md-check">

                                    <label for="checkall">
                                        <span></span>
                                        <span class="check"></span>
                                        <span class="box" id="lblcheckall"></span>
                                    </label>
                                </div>
                            </th>
                            <th>
                                Descrição
                            </th>
                            <th>
                                Data
                            </th>
                            <th class="text-right">
                                Valor   
                            </th>
                        </tr>

                        @for (int i = 0; i < Model.Comissoes.Count; i++)
                        {
                            @Html.HiddenFor(m => m.Comissoes[i].Id)
                            <tr>
                                <td>
                                    
                                    <div class="md-checkbox">
                                        @Html.CheckBoxFor(model => model.Comissoes[i].Selecionada, new { @class = "  md-check", @id = Model.Comissoes[i].Id })
                                        <label for="@Model.Comissoes[i].Id">
                                            <span></span>
                                            <span class="check"></span>
                                            <span class="box"></span>
                                        </label>
                                    </div>
                                </td>
                                <td style="padding-top: 10px">
                                    @Html.DisplayFor(m => m.Comissoes[i].Descricao)
                                </td>
                                <td style="padding-top: 10px">
                                    @Html.DisplayFor(m => m.Comissoes[i].SDataLancamento)
                                </td>
                                <td class="text-right" style="padding-top: 10px">
                                    @Html.DisplayFor(m => m.Comissoes[i].Valor)
                                </td>
                            </tr>
                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="text-right bold">@Model.Comissoes.Sum(m=>m.Valor).Value.ToString("C")</td>
                        </tr>
                    </table>
                }
                <div class="modal-footer">
                    <button type="button" class="btn dark btn-outline" data-dismiss="modal" id="btnCancelar">Cancelar</button>
                    <button type="submit" class="btn blue">Pagar selecionadas</button>
                </div>
            </div>
        }
    </div>
</div>
<script>
    $("#checkall").click(function () {
        $(".md-check").prop('checked', $(this).prop("checked"));
    });
</script>

App.MVC/Views/Comissao/Detalhe_old.cshtml
@using App.MVC.ViewModels
@model ProfissionalViewModel

@{
    ViewBag.Title = "Detalhe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='http://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script type="text/javascript" src="http://momentjs.com/downloads/moment-with-locales.min.js"></script>
@Styles.Render("~/Content/bootstrap-material-datetimepicker")
@Scripts.Render("~/bundles/bootstrap-material-datetimepicker")
@Styles.Render("~/Content/typeahead")
@Scripts.Render("~/bundles/typeahead")
@Styles.Render("~/Content/bootstrap-select")
@Scripts.Render("~/bundles/bootstrap-select")
@Scripts.Render("~/bundles/Comanda-Detalhe")
<div class="page-content">
    @Html.HiddenFor(m => m.Id, new { @id = "Id" })
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="/Home">Home</a>
            <i class="fa fa-home"></i>
        </li>
        <li>
            <a href="/Comissao/">Comissões</a>
            <i class="fa fa-percent"></i>
        </li>
        <li>
            <span class="active">Comissões do profissional</span>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12 col-xs-12">

            <div class="portlet light portlet-fit portlet-form bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class=" icon-layers font-blue-dark"></i>
                        <span class="caption-subject font-blue-dark sbold uppercase">Comissões do(a) @Model.Nome</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="form-body row">

                        <div class="col-md-12">
                            <table class="table table-hover">
                                <tr>
                                    <th class="col-xs-1 col-md-1">
                                        <div class="md-checkbox">
                                            <input type="checkbox" id="checkall" class=" md-check">

                                            <label for="checkall">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box" id="lblcheckall"></span>
                                            </label>
                                        </div>
                                    </th>
                                    <th class="col-xs-6 col-md-6">Descrição</th>
                                    <th class="col-xs-2 col-md-2">Data</th>
                                    <th class="col-xs-3 col-md-3 text-right">Valor</th>
                                </tr>
                                @foreach (var item in Model.Comissoes)
                                {
                                    <tr>
                                        <td>
                                            <div class="md-checkbox">
                                                @Html.CheckBoxFor(model => item.Selecionada, new { @class = "  md-check", @id = item.Id })
                                                <label for="@item.Id">
                                                    <span></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span> 
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            @item.Descricao
                                        </td>
                                        <td>
                                            @item.SDataLancamento
                                        </td>
                                        <td class=" text-right">
                                            @item.Valor.Value.ToString("C")
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>

                        <div class="col-md-12 col-xs-12">
                            <div class="col-md-3 col-xs-3">
                                <div class="form-group form-md-line-input">
                                    <div class="input-icon left">
                                        <br />
                                        <a class="btn yellow-lemon btnModal" style="cursor: pointer" data-toggle="modal" href="#modalFaturar">
                                            <i class="fa fa-dollar"></i>
                                            Receber
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3 col-xs-3">
                                <div class="form-group form-md-line-input">
                                    <div class="input-icon left">
                                        <strong style="font: 'Open Sans', sans-serif 14px; color: #9c9999">TOTAL SELECIONADAS</strong>
                                        <input type="text" disabled="disabled" id="subtotal" class="form-control" value="@(Model.Comissoes.Where(m => m.Selecionada).Sum(m=>m.Valor))" style="font: 20px bold" />
                                        <i>R$</i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-3">
                                <div class="form-group form-md-line-input">
                                    <div class="input-icon left">
                                        <strong style="font: 'Open Sans', sans-serif 14px; color: #9c9999">TOTAL ABERTO</strong>
                                        <input type="text" disabled="disabled" id="subtotal" class="form-control" value="@(Model.Comissoes.Sum(m=>m.Valor))" style="font: 20px bold" />
                                        <i>R$</i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="/Comissao/" class="btn default">Voltar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $("#checkall").click(function () {
        $(".md-check").prop('checked', $(this).prop("checked"));
    });

</script>

App.MVC/Views/Comissao/Index.cshtml
@using App.MVC.ViewModels
@model IEnumerable<App.MVC.ViewModels.ProfissionalViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/profile")
<div class="page-content">
    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-percent font-blue-hoki"></i>
                <span class="caption-subject font-blue-sharp bold uppercase">Comissões</span>
                <span class="caption-helper">Comissões abertas por profissional.</span>
            </div>
            <div class="actions">
                <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4">
                        <div class="portlet light bordered ">
                            <!-- STAT -->
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 col-xs-6 text-left">
                                        <span class="profile-stat-title font-grey-cascade sbold">@(item.Nome)</span>
                                        <br />
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-6 text-center">
                                        <span class="uppercase profile-stat-title">@item.Comissoes.Sum(m => m.Valor).Value.ToString("C") </span>
                                        <br />

                                        <a class="btn btn-xs blue tooltips editar" data-id="@item.Id" data-placement="top" data-original-title="Detalhar as comissões">
                                            <i class="fa fa-search"></i> Detalhar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

<div class="modal bs-modal-lg fade" id="modalEdit">
</div>

<script>
    $(".editar").click(function () {
        var id = $(this).attr("data-id");
        $("#modalEdit").load("Detalhe?id=" + id, function () {
            $("#modalEdit").modal('show');
        });
    });
</script>

App.MVC/Views/Comissao/_ReciboComissao.cshtml
@using ControleDeSalao.Infra.Cross.Security
@model IEnumerable<App.MVC.ViewModels.ComissaoViewModel>

@{
    Layout = "../Shared/_LayoutImpressao.cshtml";
}

@if (Model.Any())
{
    <table style="width: 100%">
        <tr align="center">
            <td>
                <h3>Recibo de comissão</h3>
            </td>
        </tr>
    </table>

    <table style="width: 100%">
        <tr align="center">
            <td>
                <h4>Eu, <b> @Model.First().Profissional.Nome </b>declaro ter recebido <b>@Model.Sum(m => m.Valor).Value.ToString("C")</b> no dia <b>@Model.First().DataPagamento.Value.ToString("d")</b> da empresa <b>@Cookies.NomeEmpresaLogada</b> referente as seguintes comissões de serviços prestados </h4>
            </td>
        </tr>
    </table>
    <br />
    <table class="table table-striped">
        <tr>
            <th>Data</th>
            <th>Descrição</th>
            <th>Status</th>
            <th class="text-right">Valor</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelitem => item.SDataLancamento)</td>
                <td>@Html.DisplayFor(modelitem => item.Descricao)</td>
                <td>@Html.DisplayFor(modelitem => item.Status)</td>
                <td class="text-right">@Html.DisplayFor(modelitem => item.Valor)</td>
            </tr>
        }
    </table>
    <br />
    <br />
    <table style="width: 100%">
        <tr align="center">
            <td>
                <h4>____________________ @DateTime.Today.Day de @(System.Globalization.DateTimeFormatInfo.CurrentInfo.GetMonthName(DateTime.Today.Month)) de @DateTime.Today.Year</h4>
            </td>
        </tr>
    </table>
    <br />
    <br />
    <br />
    <table style="width: 100%">
        <tr align="center">
            <td>
                <h4> ____________________________________________________________________</h4>
            </td>
        </tr>
        <tr align="center">
            <td>
                <h4>@Model.First().Profissional.Nome @(!string.IsNullOrEmpty(Model.First().Profissional.CPF) ? " - " + Model.First().Profissional.CPF : "")</h4>
            </td>
        </tr>
    </table>
}
else
{
    <table style="width: 100%">
        <tr align="center">
            <td>
                <h3>Não existem comissões para este profissional</h3>
            </td>
        </tr>
    </table>
}